### ISSUE TITLE
review of setup.md for linux ubuntu based systems, 64 bit

### ISSUE THREAD

**Issue by jspaaks** [eStep/docker-intro#1]
maybe announce what the purpose is/ what you're going to do/ what problem can be solved with docker

also note that ubuntu instructions for installing docker (but not docker-compose or docker-machine) are available in the xenon-examples tutorial: 'https://github.com/NLeSC/Xenon-examples/raw/master/doc/tutorial/xenon-tutorial.pdf' (section 2.16).

**setup.md:**
- what is docker-machine?
- command to see what distribution you are on : `lsb_release -dc`
- command to check architecture: `arch`
- I already have virtualbox, what should I do? Reinstall?

I did:

```
sudo apt-get remove virtualbox 
sudo apt-get remove virtualbox-dkms 
sudo apt-get remove virtualbox-guest-additions-iso 
sudo apt-get remove virtualbox-qt
```

I suggest moving the virtualbox stuff to after the docker stuff (why do we need it anyway? Is not clear)

I downloaded virtualbox deb file and installed by double clicking

**docker-engine:**
- what if I already have docker-engine?
- I checked with docker -v, says 1.9

**docker-machine:**

I found the curl thing confusing. Jason showed me another way some time ago (for `docker-compose`), which I find clearer:

``` bash
# cd to a directory you own
cd ~/downloads

# download the precompiled binary
curl -L https://github.com/docker/machine/releases/download/v0.5.3/docker-machine_linux-amd64 >docker-machine

# add the exectuable permission so your user is allowed to run docker-machine
chmod +x docker-machine

# move docker-machine to where docker expects it (needs sudo)
sudo mv docker-machine /usr/local/bin/
```

test if it works with `docker-machine --version` which returns

``` bash
docker-machine version 0.5.3, build 4d39a66
```

Do I need Bash completion? I decided to skip it.

**docker-compose:**

(link broken. I went to 'https://docs.docker.com/engine/installation/ubuntulinux/') 

I also had `docker-compose` already. I checked with `docker-compose --version` which returns `docker-compose version: 1.5.0`

Same deal with regard to the curl thing:

``` bash
# cd to a directory you own
cd ~/downloads

# download the precompiled binary
curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` >docker-compose

# add the exectuable permission so your user is allowed to run docker-compose
chmod +x docker-compose

# move docker-compose to where docker expects it (needs sudo)
sudo mv docker-compose /usr/local/bin/
```

There are also a couple of spelling mistakes, let me know if you want them corrected.

A general remark: I find it easier to read when the necessary information has been collected in one 'walkthrough' with a beginning and an end, as opposed to having a document link to (parts of) other documents. I realize this is more costly timewise though.

Maybe it's possible to set up a test to see if everything works? So that users can check _before_ the workshop?

**Comment by mkuzak** [comment]
Thank you Jurriaan, this is very useful. I've took your comments into account and corrected some things in the setup guide.

**Comment by jspaaks** [comment]
Sure thing, I was happy to do it.

-Jurriaan
