### ISSUE TITLE
Rational for using Virtualbox in Linux needs to be explained in install

### ISSUE THREAD

**Issue by nielsdrost** [eStep/docker-intro#2]
Using Virtualbox is not strictly necessary for Linux. 

We need to explain slightly better why using a virtual machine is a good idea anyway

**Comment by mkuzak** [comment]
Currently it says:

> This tutorial expects that you are working with linux operating system, either one
> running directly on your computer a linux vm inside VirtualBox or other virtualization
> software.

it does not suggest using VirtualBox on linux, so I don't think we should explain why you would do that.

**Comment by nielsdrost** [comment]
It _used_ to say you needed Virtualbox 9 days ago. :-)

**Comment by mkuzak** [comment]
yes but, last week we discussed it and decided that we just expect people to have Linux and then I changed a lot of stuff :)
